# config file for creating a new environment
---
# specify 'd' for dev, 'q' for QA, etc.
envtype: q

# specify a new unique number for the env
envnumber: 05

# specify the datacenter
dc: la4

# specify vCenter hostname or IP
vcenter: 10.0.0.1 

# specify vCenter login name in user@domain format
login: rkirk@ccmp 

# specify vCenter password
password: abcdef 
